<?php
// autogenerated file 29.12.2011 15:00
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * Specifies how cross-promoted items with gallery imagesshould be displayed. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GallerySortFilterCodeType.html
 *
 * @property string ShowAnyItems
 * @property string ShowItemsWithGalleryImagesFirst
 * @property string ShowOnlyItemsWithGalleryImages
 * @property string CustomCode
 */
class GallerySortFilterCodeType extends EbatNs_FacetType
{
	const CodeType_ShowAnyItems = 'ShowAnyItems';
	const CodeType_ShowItemsWithGalleryImagesFirst = 'ShowItemsWithGalleryImagesFirst';
	const CodeType_ShowOnlyItemsWithGalleryImages = 'ShowOnlyItemsWithGalleryImages';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GallerySortFilterCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_GallerySortFilterCodeType = new GallerySortFilterCodeType();

?>
