<?php
// autogenerated file 29.12.2011 15:00
// $Id: $
// $Log: $
//
require_once 'EbatNs_SimpleType.php';

/**
 *  
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/MyMessagesExternalMessageIDType.html
 *
 */
class MyMessagesExternalMessageIDType extends EbatNs_SimpleType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('MyMessagesExternalMessageIDType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_MyMessagesExternalMessageIDType = new MyMessagesExternalMessageIDType();

?>
