<?php
// autogenerated file 29.12.2011 15:00
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * Enumerated type that indicates the type and/or status of a payment hold. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/PaymentHoldStatusCodeType.html
 *
 * @property string PaymentReview
 * @property string MerchantHold
 * @property string Released
 * @property string None
 * @property string NewSellerHold
 * @property string PaymentHold
 * @property string ReleasePending
 * @property string ReleaseConfirmed
 * @property string ReleaseFailed
 * @property string CustomCode
 */
class PaymentHoldStatusCodeType extends EbatNs_FacetType
{
	const CodeType_PaymentReview = 'PaymentReview';
	const CodeType_MerchantHold = 'MerchantHold';
	const CodeType_Released = 'Released';
	const CodeType_None = 'None';
	const CodeType_NewSellerHold = 'NewSellerHold';
	const CodeType_PaymentHold = 'PaymentHold';
	const CodeType_ReleasePending = 'ReleasePending';
	const CodeType_ReleaseConfirmed = 'ReleaseConfirmed';
	const CodeType_ReleaseFailed = 'ReleaseFailed';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('PaymentHoldStatusCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_PaymentHoldStatusCodeType = new PaymentHoldStatusCodeType();

?>
