<?php
// autogenerated file 29.12.2011 15:00
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'AmountType.php';

/**
 * Seller Discounts 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SellerDiscountType.html
 *
 */
class SellerDiscountType extends EbatNs_ComplexType
{
	/**
	 * @var long
	 */
	protected $CampaignID;
	/**
	 * @var string
	 */
	protected $CampaignDisplayName;
	/**
	 * @var AmountType
	 */
	protected $ItemDiscountAmount;
	/**
	 * @var AmountType
	 */
	protected $ShippingDiscountAmount;

	/**
	 * @return long
	 */
	function getCampaignID()
	{
		return $this->CampaignID;
	}
	/**
	 * @return void
	 * @param long $value 
	 */
	function setCampaignID($value)
	{
		$this->CampaignID = $value;
	}
	/**
	 * @return string
	 */
	function getCampaignDisplayName()
	{
		return $this->CampaignDisplayName;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setCampaignDisplayName($value)
	{
		$this->CampaignDisplayName = $value;
	}
	/**
	 * @return AmountType
	 */
	function getItemDiscountAmount()
	{
		return $this->ItemDiscountAmount;
	}
	/**
	 * @return void
	 * @param AmountType $value 
	 */
	function setItemDiscountAmount($value)
	{
		$this->ItemDiscountAmount = $value;
	}
	/**
	 * @return AmountType
	 */
	function getShippingDiscountAmount()
	{
		return $this->ShippingDiscountAmount;
	}
	/**
	 * @return void
	 * @param AmountType $value 
	 */
	function setShippingDiscountAmount($value)
	{
		$this->ShippingDiscountAmount = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SellerDiscountType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__]))
				self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()],
				array(
					'CampaignID' =>
					array(
						'required' => false,
						'type' => 'long',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					),
					'CampaignDisplayName' =>
					array(
						'required' => false,
						'type' => 'string',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					),
					'ItemDiscountAmount' =>
					array(
						'required' => false,
						'type' => 'AmountType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					),
					'ShippingDiscountAmount' =>
					array(
						'required' => false,
						'type' => 'AmountType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
